Dev
vlad-marlo/gophermart pull request #4
Opened 2022-10-27 17:19 UTC by vlad-marlo

2022-10-29 11:59 UTC, kilchik requested changes

2022-10-29 11:59 UTC, kilchik commented on cmd/gophermart/main.go
> +		stringSignal = "interrupt"
Ты же можешь использовать sig.String() для получения названия сигнала

2022-10-29 11:59 UTC, kilchik commented on cmd/gophermart/main.go
> +	p.Close()
Лучше пользоваться defer для Close, иначе, например, при выполнении строчки 39, Close не вызовется

2022-10-29 11:59 UTC, kilchik commented on internal/server/helpers.go
> +	case status > 500:
`>=`

2022-10-29 11:59 UTC, kilchik commented on internal/server/helpers.go
> +	case status > 400:
`>=`

2022-10-29 11:59 UTC, kilchik commented on internal/poller/poll.go
> +		s.queue <- &task{num, user, model.StatusNew, reqID}
Что произойдет с очередью при плановом рестарте? Не потеряются ли все баллы за PENDING заказы?

2022-10-29 12:01 UTC, kilchik requested changes

2022-10-29 12:01 UTC, kilchik commented on cmd/gophermart/main.go
> +	p.Close()
Дождется ли главная горутина до завершения программы, пока OrderPoller завершит работу после Close?

2022-10-29 12:16 UTC, vlad-marlo commented on cmd/gophermart/main.go
> +	p.Close()
для этого при запуске я запрашиваю ордеры, которые подлежат обработке и поллер их обрабатывает

2022-11-07 19:54 UTC, vlad-marlo commented on internal/config/config.go
> +	AccuralSystemAddress string `env:"ACCRUAL_SYSTEM_ADDRESS" envDefault:"http://localhost:8080"`
Здесь была ошибка которую я не мог найти больше недели. Когда я начал писать проект, то я опечатался и вместо accRUal написал accURal. Сейчас я это обнаружил можно считать случайно

2022-11-07 21:43 UTC, kilchik commented on internal/config/config.go
> +	AccuralSystemAddress string `env:"ACCRUAL_SYSTEM_ADDRESS" envDefault:"http://localhost:8080"`
Здорово, что нашел! Но давай подумаем, что бы помогло найти ошибку раньше. 
1. Логирование переменных конфига при старте сервиса очень часто используется в продакшене (стоит помнить, что нельзя логировать приватную информацию). В данном случае ты бы смог определить, был ли проинициализирован AccuralSystemAddress значением по умолчанию
2. И самое главное. Сейчас для http клиента, который ходит в систему расчет баллов не выставлен таймаут, это может привести к еще более серьезным проблемам в нагруженном сервисе. Если бы ты выставил таймаут, то клиент через заданный интервал вернул ошибку при попытке сделать GET запрос, и ты бы эту ошибку увидел в логах. Для http.Client выставляется при инициализации или через context запроса. Для go-resty надо посмотреть в доке

2022-11-07 21:44 UTC, kilchik approved these changes

2022-11-08 05:34 UTC, merged